/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import consumomensual.ConsumoMensual;
import static java.lang.String.format;
/**
 *
 * @author CBN
 */
public class FrmConsumoMensual extends javax.swing.JFrame {
    public consumomensual.ConsumoMensual Consumo;
    /**
     * Creates new form FrmConsumoMensual
     */
    public FrmConsumoMensual() {
        initComponents();
        Consumo = new consumomensual.ConsumoMensual();
       txtMetrosCubicosConsumidos.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtMetrosCubicosConsumidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbtnResidencial = new javax.swing.JRadioButton();
        rbtnComercial = new javax.swing.JRadioButton();
        rbtnIndustrial = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbtnEstrato1 = new javax.swing.JRadioButton();
        rbtnEstrato2 = new javax.swing.JRadioButton();
        rbtnEstrato3 = new javax.swing.JRadioButton();
        rbtnEstrato4 = new javax.swing.JRadioButton();
        rbtnEstrato5 = new javax.swing.JRadioButton();
        rbtnEstrato6 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnCalcularConsumo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Metros Cubicos Consumidos");

        txtMetrosCubicosConsumidos.setText("jTextField1");

        jLabel2.setText("Tipo de usuario");

        buttonGroup1.add(rbtnResidencial);
        rbtnResidencial.setText("Residencial");

        buttonGroup1.add(rbtnComercial);
        rbtnComercial.setText("Comercial");

        buttonGroup1.add(rbtnIndustrial);
        rbtnIndustrial.setText("Industrial");

        jLabel3.setText("Estrato");

        buttonGroup2.add(rbtnEstrato1);
        rbtnEstrato1.setText("Estrato 1");

        buttonGroup2.add(rbtnEstrato2);
        rbtnEstrato2.setText("Estrato 2");

        buttonGroup2.add(rbtnEstrato3);
        rbtnEstrato3.setText("Estrato 3");

        buttonGroup2.add(rbtnEstrato4);
        rbtnEstrato4.setText("Estrato 4");

        buttonGroup2.add(rbtnEstrato5);
        rbtnEstrato5.setText("Estrato 5");

        buttonGroup2.add(rbtnEstrato6);
        rbtnEstrato6.setText("Estrato 6");

        jLabel4.setText("Resultado");

        lblResultado.setText("jLabel5");

        btnCalcularConsumo.setText("Calcular Consumo");
        btnCalcularConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularConsumoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtMetrosCubicosConsumidos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(rbtnResidencial)
                            .addComponent(rbtnComercial)
                            .addComponent(rbtnIndustrial)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblResultado)
                            .addComponent(jLabel4))
                        .addGap(39, 39, 39)
                        .addComponent(btnCalcularConsumo)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnEstrato6)
                    .addComponent(rbtnEstrato5)
                    .addComponent(rbtnEstrato3)
                    .addComponent(rbtnEstrato2)
                    .addComponent(rbtnEstrato1)
                    .addComponent(jLabel3)
                    .addComponent(rbtnEstrato4))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnEstrato1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnEstrato2)
                        .addGap(12, 12, 12)
                        .addComponent(rbtnEstrato3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnEstrato4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnResidencial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnComercial)
                        .addGap(12, 12, 12)
                        .addComponent(rbtnIndustrial))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMetrosCubicosConsumidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnEstrato5)
                    .addComponent(jLabel4)
                    .addComponent(btnCalcularConsumo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnEstrato6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblResultado)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularConsumoActionPerformed
        // TODO add your handling code here:
        if (rbtnResidencial.isSelected() && rbtnEstrato1.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 1, "Residencial"))); 
        }else if (rbtnComercial.isSelected()&& rbtnEstrato1.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 1, "Comercial"))); 
        }else if (rbtnIndustrial.isSelected()&& rbtnEstrato1.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 1, "Industrial"))); 
            
        }else if (rbtnResidencial.isSelected() && rbtnEstrato2.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 2, "Residencial"))); 
        }else if (rbtnComercial.isSelected() && rbtnEstrato2.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 2, "Comercial"))); 
        }else if (rbtnIndustrial.isSelected() && rbtnEstrato2.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 2, "Industrial"))); 
            
        }else if (rbtnResidencial.isSelected() && rbtnEstrato3.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 3, "Residencial"))); 
        }else if (rbtnComercial.isSelected() && rbtnEstrato3.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 3, "Comercial"))); 
        }else if (rbtnIndustrial.isSelected() && rbtnEstrato3.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 3, "Industrial"))); 
            
            
        }else if (rbtnResidencial.isSelected() && rbtnEstrato4.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 4, "Residencial")));   
        }else if (rbtnComercial.isSelected() && rbtnEstrato4.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 4, "Comercial")));   
        }else if (rbtnIndustrial.isSelected() && rbtnEstrato4.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 4, "Industrial")));   
            
        }else if (rbtnResidencial.isSelected() && rbtnEstrato5.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 5, "Redidencial")));   
        }else if (rbtnComercial.isSelected() && rbtnEstrato5.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 5, "Comercial")));   
        }else if (rbtnIndustrial.isSelected() && rbtnEstrato5.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 5, "Industrial")));   
            
        }else if (rbtnResidencial.isSelected() && rbtnEstrato6.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 6, "Residencial")));   
        }else if (rbtnComercial.isSelected() && rbtnEstrato6.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 6, "Comercial")));   
        }else if (rbtnIndustrial.isSelected() && rbtnEstrato6.isSelected()){
            lblResultado.setText(Double.toString(Consumo.Calculo(Double.parseDouble(txtMetrosCubicosConsumidos.getText()), 5000, 6, "Industrial")));   
        }
        
    }//GEN-LAST:event_btnCalcularConsumoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConsumoMensual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConsumoMensual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConsumoMensual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsumoMensual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConsumoMensual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularConsumo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton rbtnComercial;
    private javax.swing.JRadioButton rbtnEstrato1;
    private javax.swing.JRadioButton rbtnEstrato2;
    private javax.swing.JRadioButton rbtnEstrato3;
    private javax.swing.JRadioButton rbtnEstrato4;
    private javax.swing.JRadioButton rbtnEstrato5;
    private javax.swing.JRadioButton rbtnEstrato6;
    private javax.swing.JRadioButton rbtnIndustrial;
    private javax.swing.JRadioButton rbtnResidencial;
    private javax.swing.JTextField txtMetrosCubicosConsumidos;
    // End of variables declaration//GEN-END:variables
}
