
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class FrmRegistrosEscolares extends javax.swing.JFrame {
    
    DefaultTableModel mt = new DefaultTableModel();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRegistrosEscolares.class.getName());

    /**
     * Creates new form FrmRegistrosEscolares
     */
    public FrmRegistrosEscolares() {
        
        initComponents();
        
        txtNombre.setText("");
        txtCalificacion1.setText("");
        txtCalificacion2.setText("");
        txtCalificacion3.setText("");
        
        String ids [] = {"Nombre","Calificacion 1","Calificacion 2", "Calificacion 3","Promedio"};
        mt.setColumnIdentifiers(ids);
        jTable1.setModel(mt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblNombre = new javax.swing.JLabel();
        lblCalificacion1 = new javax.swing.JLabel();
        lblCalificacion3 = new javax.swing.JLabel();
        lblCalificacion2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCalificacion1 = new javax.swing.JTextField();
        txtCalificacion2 = new javax.swing.JTextField();
        txtCalificacion3 = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblNombre.setText("Nombre");

        lblCalificacion1.setText("Calificacion 1");

        lblCalificacion3.setText("Calificacion 3");

        lblCalificacion2.setText("Calificacion 2");

        txtCalificacion1.setText("jTextField1");

        txtCalificacion2.setText("jTextField2");

        txtCalificacion3.setText("jTextField3");

        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(this::btnAñadirActionPerformed);

        btnRemover.setText("Remover");
        btnRemover.addActionListener(this::btnRemoverActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAñadir)
                                .addGap(88, 88, 88)
                                .addComponent(btnRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnActualizar)))
                        .addContainerGap(133, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addGap(55, 55, 55))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombre)
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCalificacion1)
                            .addComponent(txtCalificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCalificacion2)
                            .addComponent(txtCalificacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCalificacion3)
                            .addComponent(txtCalificacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblCalificacion1)
                    .addComponent(lblCalificacion2)
                    .addComponent(lblCalificacion3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCalificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCalificacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCalificacion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadir)
                    .addComponent(btnRemover)
                    .addComponent(btnActualizar))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        // TODO add your handling code here:
        String nombre = String.valueOf(txtNombre.getText());
        double cali1 = Double.valueOf(txtCalificacion1.getText());
        double cali2 = Double.valueOf(txtCalificacion2.getText());
        double cali3 = Double.valueOf(txtCalificacion3.getText());
        double prom = (cali1 + cali2 + cali3)/3;
        mt.addRow(new Object[]{nombre,cali1,cali2,cali3,prom});
        txtNombre.setText("");
        txtCalificacion1.setText("");
        txtCalificacion2.setText("");
        txtCalificacion3.setText("");
        
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        mt.removeRow(jTable1.getSelectedRow());
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        mt.setValueAt(txtNombre.getText(), jTable1.getSelectedRow(), 0);
        mt.setValueAt(txtCalificacion1.getText(), jTable1.getSelectedRow(), 1);
        mt.setValueAt(txtCalificacion2.getText(), jTable1.getSelectedRow(), 2);
        mt.setValueAt(txtCalificacion3.getText(), jTable1.getSelectedRow(), 3);
        mt.setValueAt((Double.valueOf(txtCalificacion1.getText()) + 
                Double.valueOf(txtCalificacion2.getText()) + 
                Double.valueOf(txtCalificacion3.getText()))/3, 
                jTable1.getSelectedRow(), 4);
        txtNombre.setText("");
        txtCalificacion1.setText("");
        txtCalificacion2.setText("");
        txtCalificacion3.setText("");
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmRegistrosEscolares().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCalificacion1;
    private javax.swing.JLabel lblCalificacion2;
    private javax.swing.JLabel lblCalificacion3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtCalificacion1;
    private javax.swing.JTextField txtCalificacion2;
    private javax.swing.JTextField txtCalificacion3;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
